### PR TITLE
Bugfix/gh 95 undeploy with purge

### LINKED ISSUE #95: Yorc failure at undeployment leaves an app unpurged on Yorc server while undeployed in Alien4Cloud
# Issue Type

* [X] Bug report
* [ ] Documentation issue report
* [ ] Improvement request

## Description

When undeploying applications from Alien4Cloud, the application is expected to be undeployed, then purged from Yorc Server.

In some cases, it happens that the application is undeployed but not purged on Yorc Server side.

Looking at Alien4Cloud logs, a Yorc server error is reported : Task with id "xxx" and status "INITIAL" already exists for target "Deployment PAAS ID"

As a consequence, next attempt to deploy the application from Alien4Cloud will fail as Yorc has already an application unpurged with the same name.

Looking at the code, in a loop in UndeployTask, it can happen that this task will try twice to change the status to UNDEPLOYED,
first here: https://github.com/ystia/yorc-a4c-plugin/blob/develop/alien4cloud-yorc-plugin/src/main/java/org/ystia/yorc/alien4cloud/plugin/UndeployTask.java#L118
Then here: https://github.com/ystia/yorc-a4c-plugin/blob/develop/alien4cloud-yorc-plugin/src/main/java/org/ystia/yorc/alien4cloud/plugin/UndeployTask.java#L163
As the call changing the status to UNDEPLOYED is attempting to perform a purge, we can have two attempts to purge a deployment. And the second attempt will fail. 

Other issue to fix at the same time : a null pointer exception can happen at:
https://github.com/ystia/yorc-a4c-plugin/blob/develop/alien4cloud-yorc-plugin/src/main/java/org/ystia/yorc/alien4cloud/plugin/EventListenerTask.java#L74
because the call to jrdi.getInstanceInformations() is done before (instead of after) checking if jrdi is null

## Priority

Medium

* High = We should stop anything we are doing and do this. If you're writing this calmly, you should probably choose another option. If it's really that urgent, please make sure we read this.
* Medium = It's important that we do this within a few days.
* Low = We will consider this on our next sprint planning.

(Please be aware that your priority may not match ours, we'll use this as guidance only).

### PR DESCRIPTION
**Pull request by stebenoist**
# Pull Request description

## Description of the change
Execute undeploy and purge in one Yorc REST request

## Applicable Issues
fixes #95

### CODE REVIEW

File: alien4cloud-yorc-plugin/src/main/java/org/ystia/yorc/alien4cloud/plugin/UndeployTask.java [hunk 1]
```diff
@@ -68,40 +69,49 @@ public void run() {
...
             if (taskUrl == null) {
                 // Assumes already undeployed
                 orchestrator.changeStatus(paasId, DeploymentStatus.UNDEPLOYED);
                 done = true;
             }
         }
-        catch (YorcRestException jre) {
+        catch(YorcRestException jre){
+            // If 400 code (bad request)  is returned, we retry requesting purge during at most 5 minutes
+            if (jre.getHttpStatusCode() == 400) {
```
Comment (loicalbertin) [inline alien4cloud-yorc-plugin/src/main/java/org/ystia/yorc/alien4cloud/plugin/UndeployTask.java]: Why do we implement a retry here?

Comment (stebenoist) [reply alien4cloud-yorc-plugin/src/main/java/org/ystia/yorc/alien4cloud/plugin/UndeployTask.java]: It's legacy. Don't know why it has been done

**Comment by loicalbertin** [comment]
To be backported on  3.1
